substitutions:
  name: "mitp-heat-pump"
  friendly_name: "mITP Heat Pump"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

  project:
    name: "tinwer.mahtanarm"
    version: "1.1"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Load the mitsubishi_itp component from this repo for now (hopefully eventually it will merged in ESPHome)
external_components:
  - source: github://muart-group/esphome@dev
    components: [ mitsubishi_itp ]

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://tinwer-group/mahtanar/esphome-configs/mahtanar-ethernet-default.yaml@1.1-release
  import_full_config: true

logger:
  # Serial logging disabled to support communication with thermostat.  Can be reenabled by disabling tstat_uart below, and specifying baud_rate.
  baud_rate: 0 

# Enable Home Assistant / ESPHome API
api:

# Enable ota updates (no password here, but one will be generated during adoption)
ota:
  platform: esphome

# Enable Ethernet (no WiFi can be configured with Ethernet)
ethernet:
  type: W5500
  mosi_pin: GPIO09
  miso_pin: GPIO08
  clk_pin: GPIO10
  cs_pin: GPIO5
  reset_pin: GPIO04
  interrupt_pin: GPIO03
  clock_speed: 25MHz

# Define mitsubishi_itp climate component
climate:
  - platform: mitsubishi_itp
    uart_heatpump: hp_uart
    uart_thermostat: tstat_uart # This and the uart component below can be removed if no thermostat connected
    update_interval: 6s # This should be a relatively safe default, but can be adjusted if desired

# Define UARTs connected to heat pump and thermostat
uart:
  - id: hp_uart
    baud_rate: 2400 # For some equipment this may need to be 9600
    parity: EVEN
    rx_pin:
      number: GPIO7
    tx_pin:
      number: GPIO6
  - id: tstat_uart
    baud_rate: 2400 # For some equipment this may need to be 9600
    parity: EVEN
    rx_pin:
      number: GPIO20
    tx_pin:
      number: GPIO21