substitutions:
  name: "muart-heat-pump"
  friendly_name: "mUART Heat Pump"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true

  project:
    name: "Tinwer MahtanarM"
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Load the mitsubishi_uart component from this repo for now (hopefully eventually it will merged in ESPHome)
external_components:
  - source: github://muart-group/esphome@dev
    components: [ mitsubishi_uart ]

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://tinwer-group/mahtanar/esphome-configs/mahtanar-wifi-default.yaml@1.0-release
  import_full_config: false # or true

logger:
  # Serial logging disabled to support communication with thermostat.  Can be reenabled by disabling tstat_uart below.
  baud_rate: 0 

# Enable Home Assistant API
api:

ota:

 # Enable WiFi and captive portal for provisioning
wifi:
  ap:
    ssid: "mUART Setup"
    password: "mahtanar"

captive_portal:

# Define mitsubishi_uart component
mitsubishi_uart:
  heatpump_uart: hp_uart
  thermostat_uart: tstat_uart # This and the uart component below can be removed if no thermostat connected
  update_interval: 6s # This should be a relatively safe default, but can be adjusted if desired

# Define UARTs connected to heat pump and thermostat
uart:
  - id: hp_uart
    baud_rate: 2400 # For some equipment this may need to be 9600
    parity: EVEN
    rx_pin:
      number: GPIO7
    tx_pin:
      number: GPIO6
  - id: tstat_uart
    baud_rate: 2400 # For some equipment this may need to be 9600
    parity: EVEN
    rx_pin:
      number: GPIO20
    tx_pin:
      number: GPIO21